### ISSUE TITLE
Links in the documentation are not working

### ISSUE THREAD

**Issue by jdacoello** [talespaiva/STEP#1]
When you click on any of the concepts in the documentation html of the ontology, it takes you to a link that is broken. 
![Screenshot 2021-09-19 at 23 08 50](https://user-images.githubusercontent.com/8550265/133943084-213acb87-c4c9-40f9-998f-9fe949418381.png)

**Comment by talespaiva** [comment]
It seems that some pages generated by Parrot have this issue. Thanks for pointing this out.
